const SUMMER_START = 1561075200;
const SUMMER_END = 1569196800;

const SUMMER_RATE = 10;
const WINTER_RATE = 20;
const WINTER_SERVICE_CHARGE = 30;

module.exports = {
    SUMMER_START,
    SUMMER_END,
    SUMMER_RATE,
    WINTER_RATE,
    WINTER_SERVICE_CHARGE
}